# Generated by Django 6.0 on 2025-12-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('registered_date', models.DateField()),
                ('pref', models.IntegerField()),
            ],
            options={
                'ordering': ['customer_no'],
            },
        ),
    ]
