# Generated by Django 6.0 on 2025-12-30 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.prefecture', verbose_name='都道府県'),
        ),
    ]
