# Generated by Django 6.0 on 2025-12-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_prefecture_alter_customer_pref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True, verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['product_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_no'], 'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.IntegerField(verbose_name='会員番号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='売上日')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='金額')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer', verbose_name='顧客')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customer.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '売上',
                'verbose_name_plural': '売上',
                'ordering': ['-sale_date', '-id'],
            },
        ),
    ]
